---
title: "Ten simple rules for publishing a research compendium"
---

- add all data and code created by you
- properly reference data and code created by others (use DOIs as much as possible)
- follow language guidelines for packaging (ref "R and friends" paper)
- understand copyright and licensing for data, code, and text (ref Stodden paper, contributors guide), choose wisely for your own data, make sure not to break licenses of used data and code
- explain the basics of the compendium in a specific section in your article
- add a single entry point for the computations (Makefile, main.sh, run.R, but ideally a literate programming file)
- write instructions for different levels ("explain to me like I'm five", but also document for yourself)
- get a colleague to review it (fallback: follow your own instructions on a different computer/VM, ..)
- describe computational environment (fallback: text, better: executable instructions like Dockerfile, Vagrantfile, make easily explorable - Binder)
- export snapshot of computational environment
- publish the whole compendium in a repository (own discretion, do not blindingly publish parts independently, concrete software version and used data only, do not embed software and data paper)
- tag the compendium (and see if it is disoverable via https://research-compendium.science)
- curate meaningful links and metadata (cf. zenodo metadata, ultimate goal is research compendium as a [first level type in publication metadata](https://support.crossref.org/hc/en-us/sections/202832823-Crossref-metadata))
  - https://support.crossref.org/hc/en-us/articles/214357426
- spread the word and be open
  - talk to three other people about how they could create a resarch compendium for a specific piece of research of theirs (snowball effect!)
  - contributors guide


## Acknowledgements

...
